apiVersion: apps/v1
kind: Deployment

metadata:
  name: peyk

spec:
  replicas: 2
  selector:
    matchLabels:
      app: peyk
  template:
    metadata:
      labels:
        app: peyk
    spec:
      containers:
        - name: peyk
          image: tintoka/peyk-image:latest
          ports:
            - containerPort: 80
              name: peyk
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "600Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: bepa-config
            - secretRef:
                name: bepa-secret

