apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
spec:
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  volumeName: db-vol
  resources:
    requests:
      storage: 100Mi