apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configmap.name}}
data:
  DB_TIMEOUT: "10"
  DB_NAME: "cc-finalProject"
  DB_HOST: "db"
  DB_PORT: "3306"
  MAIL_SERVICE_URL: "https://api.mailgun.net/v3/sandbox6748cfee9f664439be9af8f9eca357f4.mailgun.org/messages"
  MAIL_SERVICE_KEY: "f6963d9b50b5f877eb9dba76d7b75dcf-7764770b-29bb0025"
  COIN_NEWS_HOST: "http://coinnews"
  COIN_NEWS_PORT: "8000"
  PEYK_API_HOST: "0.0.0.0"
  PEYK_API_PORT: "80"
  MYSQL_DATABASE: "cc-finalProject"
  PEYK_HOST: "http://peyk"
  PEYK_PORT: "80"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coinnews-configs
  labels:
    app: coinnews
    kubernetes.config: yaml
    kubernetes.app: data-source
  annotations:
    config-type: yaml
data:
  config.yml: |+
    http_port: 8000
    worker_enable: true
    worker_interval: 10
    change_probability: 3
    change_factor: 7
    units:
      - name: bitcoin
        value: 50000
      - name: dogecoin
        value: 23000
      - name: usdcoin
        value: 8000
      - name: zerocoin
        value: 7500
      - name: unocoin
        value: 100
      - name: colocoin
        value: 9240
      - name: somecoin
        value: 80