apiVersion: v1
kind: Service

metadata:
  name: db

spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service

metadata:
  name: coinnews
  labels:
    kubernetes.app: data-source
    app: coinnews

spec:
  type: ClusterIP
  selector:
    app: coinnews
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.peykName}}

spec:
  selector:
    app: {{ .Values.peykName}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service

metadata:
  name: gui

spec:
  selector:
    app: gui
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
