apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-vol
  labels:
    type: local
spec:
  capacity:
   storage: 400Mi
  accessModes:
   - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data"

